papers = {};
duplicates = {};
m=1;
d=1;
citations = importfile('citations0813.txt');
for i = 1:3799
    line = convertStringsToChars(citations(i));
    try
        if line(1) ~= '@'
            continue;
        end
    catch
        continue;
    end
    j=2;
    while line(j)~='{'
        a = line(j);
        j = j+1;
    end
    j = j+1;
    k = j;
    while ~isstrprop(line(j),'digit')
        a = line(j);
        j = j+1;
    end
    author = line(k:j-1);
    k = j;
    while isstrprop(line(j),'digit')
        j = j+1;
    end
    year = line(k:j-1);
    source = [author,year];
    if any(strcmp(papers,upper(source)))
        step = 1;
        firstChar = ' ';
        title = 'title not found';
        while firstChar ~='@' && step<25
            line = convertStringsToChars(citations(i+step));
            try
                j=1;
                while line(j) ==' '
                    j = j+1;
                end
                if line(j:j+4) == 'title'
                    title = line(j+5:end);
                    break;
                end
            catch
            end
            step = step+1;
            line = convertStringsToChars(citations(i+step+1));
            try
                firstChar = line(1);
            catch
                fprintf('Error in %d\n',i)
            end
        end
        
        duplicates{d} = strcat('line',num2str(i),', ',source,', ',title(3:end-2));
        d = d+1;
        continue;
    end
    papers{m} = upper(source);
    m = m+1;
end




function citations0813 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CITATIONS0813 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  CITATIONS0813 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  citations0813 = importfile("C:\Users\Alpha\Documents\andy\citations0813.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Aug-2021 11:02:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "articleschaferling205chiral";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "articleschaferling205chiral", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "articleschaferling205chiral", "EmptyFieldRule", "auto");

% Import the data
citations0813 = readmatrix(filename, opts);

end